export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A futuristic cityscape at sunset, with flying cars and holographic billboards.",
  "A mystical forest with glowing mushrooms and ethereal creatures.",
  "An underwater kingdom ruled by mermaids and adorned with vibrant coral reefs.",
  "A steampunk-style airship soaring through the clouds.",
  "A magical library filled with floating books and enchanted scrolls.",
  "A floating island in the sky with waterfalls cascading down its sides.",
  "A space explorer standing on the surface of a distant alien planet.",
  "A lush garden of oversized flowers and talking animals.",
  "An ancient castle on a cliff overlooking a stormy sea.",
  "A cyberpunk city skyline with neon lights and bustling streets.",
  "A serene mountain landscape with a hidden waterfall and tranquil pond.",
  "A group of wizards casting spells in a hidden enchanted grove.",
  "A bustling market in a Middle Eastern desert city.",
  "A post-apocalyptic wasteland with remnants of advanced technology.",
  "A dragon and a phoenix engaged in an epic aerial battle.",
  "A futuristic laboratory with advanced scientific equipment.",
  "A hidden cave filled with glittering gemstones and mysterious artifacts.",
  "A Viking ship sailing through icy waters towards a distant island.",
  "A space station orbiting a distant planet, surrounded by stars.",
  "A whimsical candyland with giant lollipops and candy-shaped mountains.",
  "A steam-powered mech warrior defending a city from monstrous creatures.",
  "A hidden temple deep within a lush jungle, guarded by ancient statues.",
  "A cosmic ballet of planets and celestial bodies in a distant galaxy.",
  "A time traveler exploring different historical eras.",
  "A majestic waterfall cascading into a bioluminescent pool.",
  "A haunted mansion with ghostly apparitions and creaking doors.",
  "A futuristic sports arena where alien creatures compete.",
  "A city of the future where nature and technology coexist harmoniously.",
  "A desert oasis surrounded by palm trees and shimmering sand dunes.",
  "An alien landscape with bizarre rock formations and unusual flora.",
  "A wizard's tower with spiraling staircases and magical experiments.",
  "A serene lakeside cabin surrounded by towering mountains.",
  "A hidden grotto filled with crystals that emit a soothing glow.",
  "A celestial being emerging from a nebula in deep space.",
  "An underwater cave with glowing jellyfish and bioluminescent creatures.",
  "A floating marketplace where traders sell goods from airships.",
  "A city engulfed in a mystical aurora borealis.",
  "An ancient Egyptian pyramid illuminated by the setting sun.",
  "A futuristic train speeding through a high-tech tunnel.",
  "A secret garden hidden behind a towering waterfall.",
  "A giant mechanical tree housing an entire civilization.",
  "A serene zen garden with perfectly raked sand and bonsai trees.",
  "A bustling intergalactic spaceport with ships from different worlds.",
  "A medieval village nestled at the base of a majestic mountain.",
  "An enchanted forest with trees that come to life at night.",
  "A frozen tundra with ice caves and shimmering auroras.",
  "A city on the back of a massive roaming creature.",
  "A whimsical circus with acrobats, clowns, and magical acts.",
  "A futuristic underwater research station exploring the mysteries of the deep.",
  "A floating city above the clouds, accessible only by airships.",
];